name: ci

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'documentation/**'
  pull_request:
    branches:
      - master
      - main
    paths:
      - 'documentation/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. FULL‑DEPTH CHECKOUT
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0     # ensure we fetch all history so gh-pages can be seen/created
          fetch-tags: true

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material

      # ————— Begin SHA & Injection —————

      - name: Get commit SHA
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Inject SHA into docs
        run: |
          sed -i "s/BUILD_SHA_HERE/${SHA}/g" documentation/docs/news.md

      - name: Install Mike
        run: pip install mike

      # OPTIONAL: Fetch the gh-pages branch if it already exists
      - name: Fetch existing gh-pages (if any)
        run: git fetch origin gh-pages:gh-pages || true

      # ————— Deploy with Mike —————

      - name: Deploy docs with mike
        working-directory: documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mike deploy "${SHA}" --branch gh-pages --push
          mike set-default "${SHA}" --branch gh-pages --push
